version: '3.6'

services:
  greenlight:
    image: bigbluebutton/greenlight:v2
    restart: unless-stopped
    env_file: .env
    environment:
      DB_ADAPTER: postgresql
      DB_HOST: postgres
      DB_NAME: greenlight
      DB_USERNAME: postgres
      DB_PASSWORD: password
      BIGBLUEBUTTON_ENDPOINT: ${GREENLIGHT_ENDPOINT}
      BIGBLUEBUTTON_SECRET: ${SHARED_SECRET}
      SECRET_KEY_BASE: ${RAILS_SECRET}
    ports:
      - 10.7.7.1:5000:80
  postgres:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_DB: greenlight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
