version: '3.6'
services:
  https_proxy:
    image: valian/docker-nginx-auto-ssl
    restart: unless-stopped
    volumes:
      - ssl_data:/etc/resty-auto-ssl
      - ./mod/https/${HTTPS_SITE_FILE}:/etc/nginx/conf.d/bbb-docker.conf
    environment:
      ALLOWED_DOMAINS: ${CERTIFICATE_DOMAINS}
    network_mode: host

volumes:
  ssl_data:
    name: ssl_data
