version: '3.6'
services:
  webhooks:
    build: mod/webhooks
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
      SHARED_SECRET: ${SHARED_SECRET}
    depends_on:
      - redis
    networks:
      bbb-net:
        ipv4_address: 10.7.7.15